# Generated by Django 4.1.4 on 2023-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('V', 'Vigor'), ('A', 'Anulada'), ('S', 'Suspendida')], max_length=250, verbose_name='Estado Póliza')),
            ],
            options={
                'verbose_name': 'PolicyStatus',
            },
        ),
        migrations.CreateModel(
            name='ReceiptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Estado Recibo')),
            ],
            options={
                'verbose_name': 'ReceiptStatus',
            },
        ),
    ]
