# Generated by Django 4.1.4 on 2023-01-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_policystatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policystatus',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Estado Póliza'),
        ),
    ]
