# Generated by Django 4.1.4 on 2023-01-11 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0004_policystatus_code_receiptstatus_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.BigIntegerField(verbose_name='Número Póliza')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Alta')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('cancellation_date', models.DateTimeField(null=True, verbose_name='Fecha Anulación')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Titular')),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.policystatus', verbose_name='Estado Póliza')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.BigIntegerField(verbose_name='Número Recibo')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha Final')),
                ('payment_date', models.DateField(null=True, verbose_name='Fecha Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Importe')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='policies.policy')),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.receiptstatus', verbose_name='Estado Recibo')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
            },
        ),
    ]
