# Generated by Django 4.1.4 on 2023-01-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_alter_policy_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_code',
            field=models.CharField(max_length=250, unique=True, verbose_name='Número Recibo'),
        ),
    ]
