# Generated by Django 4.1.4 on 2023-01-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_alter_receipt_receipt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_code',
            field=models.CharField(max_length=250, unique=True, verbose_name='Número Póliza'),
        ),
    ]
