# Generated by Django 4.1.4 on 2023-01-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0009_alter_policy_policy_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.policystatus', verbose_name='Estado Póliza'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.receiptstatus', verbose_name='Estado Recibo'),
        ),
    ]
