# Generated by Django 4.1.4 on 2023-01-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_policy_suspension_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cancellation_date',
            field=models.DateField(null=True, verbose_name='Fecha Cancelación'),
        ),
    ]
