# Generated by Django 4.1.4 on 2023-01-11 14:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0012_receipt_cancellation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 15, 52, 26, 363502), verbose_name='Fecha Alta'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='policy', to=settings.AUTH_USER_MODEL, verbose_name='Titular'),
        ),
    ]
