# Generated by Django 4.1.4 on 2023-01-12 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0013_alter_policy_created_alter_policy_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 16, 0, 26, 985075), verbose_name='Fecha Alta'),
        ),
    ]
