# Generated by Django 4.1.4 on 2023-01-16 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0014_alter_policy_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 12, 24, 31, 14884), verbose_name='Fecha Alta'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cancellation_date',
            field=models.DateField(null=True, verbose_name='Fecha Anulación'),
        ),
    ]
