# Generated by Django 4.1.4 on 2023-01-17 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0015_alter_policy_created_alter_receipt_cancellation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 14, 45, 43, 764734), verbose_name='Fecha Alta'),
        ),
    ]
