# Generated by Django 4.1.4 on 2023-01-17 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0016_alter_policy_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 14, 48, 25, 347247), verbose_name='Fecha Alta'),
        ),
    ]
