# Generated by Django 4.1.4 on 2023-01-17 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0018_alter_policy_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 14, 50, 56, 247557), verbose_name='Fecha Alta'),
        ),
    ]
